name: KaliLiveControl
on: push
jobs:
  kali-live:
    runs-on: ubuntu-latest
    container:
      image: kalilinux/kali-rolling:latest
    steps:
      - name: Open Live Tunnel
        run: |
          apt-get update
          apt-get install -y tmate curl
          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready
          echo "Connect to your Kali Server using this command:"
          tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
          sleep 6h
